"""initial schema: activity, award, draw_order

Revision ID: 965c30f28d00
Revises: 
Create Date: 2026-09-14 10:44:52.849607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '965c30f28d00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stock_total', sa.Integer(), nullable=False),
    sa.Column('stock_surplus', sa.Integer(), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_time > start_time', name='ck_activity_time'),
    sa.CheckConstraint('stock_surplus >= 0 AND stock_surplus <= stock_total', name='ck_activity_stock'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', name='uk_activity_id')
    )
    op.create_table('draw_order',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('award_id', sa.BigInteger(), nullable=True),
    sa.Column('draw_state', sa.String(length=16), nullable=False),
    sa.Column('award_state', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uk_order_id'),
    sa.UniqueConstraint('request_id', name='uk_request_id')
    )
    op.create_index('idx_user_activity_created', 'draw_order', ['user_id', 'activity_id', 'created_at'], unique=False)
    op.create_table('award',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('award_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('award_type', sa.String(length=16), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('stock_total', sa.Integer(), nullable=False),
    sa.Column('stock_surplus', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('stock_surplus >= 0 AND stock_surplus <= stock_total', name='ck_award_stock'),
    sa.CheckConstraint('weight > 0', name='ck_award_weight'),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.activity_id'], name='fk_award_activity'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('award_id', name='uk_award_id')
    )
    op.create_index('idx_activity_id', 'award', ['activity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_id', table_name='award')
    op.drop_table('award')
    op.drop_index('idx_user_activity_created', table_name='draw_order')
    op.drop_table('draw_order')
    op.drop_table('activity')
    # ### end Alembic commands ###
